### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by pxninja** [threatgrid/ctia-ui#16]
![screen shot 2016-11-14 at 2 51 08 pm](https://cloud.githubusercontent.com/assets/17751642/20282315/dca30adc-aa79-11e6-8f3c-b640108b2146.png)

**Comment by craigbro** [comment]
Since we are going to use SAML (a single sign on tech) for Tenzin, we likely won't ever show users a login, at least not when configured to use SAML.

**Comment by oakmac** [comment]
Does this mean that we will not control the login user experience? Where will the user login from?

**Comment by craigbro** [comment]
Actually, in discussions with the CTA team that implemented a SAML client or the AMP SAML service, and getting details on what our exact flow will be.

**Comment by craigbro** [comment]
I have confirmed that we will not control the login page.

What happens is roughly:
1. User wants to login, let's say they are going to tenzin.amp.cisco.com/...
2. We see the user doesn't have a session and needed to login, so we send a redirect to the SAML Identity Provider (IDP), at console.amp.cisco.com/saml with a special request token as query string param.
3. The IDP will see if that user is already authenticated to them, and if not present them with a login.  Once authenticated, they redirect the user back to our app with a token that we can validate.

**Comment by pxninja** [comment]
Closing issue, as we no longer control the login page.
