### ISSUE TITLE
Vocabularies - Expanded Row

### ISSUE THREAD

**Issue by pxninja** [threatgrid/ctia-ui#31]

**Comment by pxninja** [comment]
There appears to be no Vocabularies map?
https://github.com/threatgrid/ctim/tree/master/doc

**Comment by oakmac** [comment]
I'm not sure "Vocabularies" is going to have an Entity List table at all.

I think we just need a way for the user to manage the pre-defined lists that appear throughout the UI on this page.

**Comment by pxninja** [comment]
Per Craig - This will not be controllable by the user at this time.
